vich_uploader:
    db_driver: orm

    metadata:
        type: attribute


    mappings:
        car:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false

        carPdf:
            uri_prefix: /uploads/pdfs
            upload_destination: '%kernel.project_dir%/public/uploads/pdfs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
